version: '3'
services:
  web:
    build: .
    container_name: "server"
    image: containers.cisco.com/gvedevnet/viptela-template-migration:latest
    ports:
      - "5000:5000"
    environment:
      TZ: "Asia/Singapore"

# "America/Los_Angeles"
# "Asia/Singapore"
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones “TZ Database Name”